name: Build Windows Executable

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  #use Microsoft's setup-msbuild action

    - name: Install python packages
      run: |
        # Create the python-embedded directory if it doesn't exist
        $pythonEmbeddedDir = ".\python-embedded"
        If (-Not (Test-Path $pythonEmbeddedDir)) {
            New-Item -ItemType Directory -Force -Path $pythonEmbeddedDir
        }

        # Download the embedded Python zip
        curl https://www.python.org/ftp/python/3.11.4/python-3.11.4-embed-win32.zip -o "python.zip"

        # Extract the Python zip
        Expand-Archive -Path "python.zip" -DestinationPath $pythonEmbeddedDir -Force

        # Download pip.pyz
        curl https://bootstrap.pypa.io/pip/pip.pyz -o "$pythonEmbeddedDir\pip.pyz"

        # Install packages from requirements.txt using the embedded Python and pip.pyz
        & "$pythonEmbeddedDir\python.exe" "$pythonEmbeddedDir\pip.pyz" install -r .\requirements.txt --target=".\Lib\site-packages\"

        Remove-Item -Recurse -Force $pythonEmbeddedDir python.zip
      shell: pwsh


    - name: Zip python packages
      run: |
        Compress-Archive -Path .\Lib -DestinationPath Lib.zip
        Move-Item -Path Lib.zip -Destination AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\Lib.zip -Force
        Remove-Item -Recurse -Force .\Lib


    # - name: Zip Project Files
    #   run: |
    #     $exclude = @('AzerothAuctionAssassin-windows', '.github', '.git', '.gitignore')
    #     $items = Get-ChildItem -Path . -Recurse | Where-Object { $exclude -notcontains $_.Name }
    #     Compress-Archive -Path $items.FullName -DestinationPath app.zip
    #     Move-Item -Path app.zip -Destination AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\app.zip -Force

    - name: update version number
      run: |
        echo 1.0.6 > AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\appVersion.txt

    - name: Build EXE
      run: |
        msbuild AzerothAuctionAssassin-windows\AzerothAuctionAssassin.sln -restore -t:Publish /p:Configuration=Release /p:PublishProfile=".\AzerothAuctionAssassin\Properties\PublishProfiles\FolderProfile.pubxml"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.6
        release_name: Release v1.0.6
        draft: false
        prerelease: false

    - name: Upload Executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\AzerothAuctionAssassin-windows\AzerothAuctionAssassin\bin\Release\net8.0-windows\publish\win-x86\AzerothAuctionAssassin.exe
        asset_name: AzerothAuctionAssassin.exe
        asset_content_type: application/octet-stream
