name: Build Windows Executable

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  #use Microsoft's setup-msbuild action

    - name: Install python packages
      run: pip install -r requirements.txt  --target=.\Lib\site-packages

    - name: Zip python packages
      run: |
        Compress-Archive -Path .\Lib -DestinationPath Lib.zip
        Move-Item -Path Lib.zip -Destination AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\Lib.zip -Force
        Remove-Item -Recurse -Force .\Lib


    - name: Zip Project Files
      run: |
        $exclude = @('AzerothAuctionAssassin-windows', '.github', '.git', '.gitignore')
        $items = Get-ChildItem -Path . -Recurse | Where-Object { $exclude -notcontains $_.Name }
        Compress-Archive -Path $items.FullName -DestinationPath app.zip
        Move-Item -Path app.zip -Destination AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\app.zip -Force

    - name: update version number
      run: |
        echo 1.0.4 > AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\appVersion.txt

    - name: Build EXE
      run: |
        msbuild AzerothAuctionAssassin-windows\AzerothAuctionAssassin.sln /p:Configuration=Release /p:PublishProfile=".\AzerothAuctionAssassin\Properties\PublishProfiles\FolderProfile.pubxml"  -restore -t:Publish
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.5
        release_name: Release v1.0.5
        draft: false
        prerelease: false

    - name: Upload Executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\AzerothAuctionAssassin-windows\AzerothAuctionAssassin\bin\Release\net8.0-windows\publish\win-x86\AzerothAuctionAssassin.exe
        asset_name: AzerothAuctionAssassin.exe
        asset_content_type: application/octet-stream
